version: "3.9"

services:
  app1:
    build: ./app1
    container_name: app1
    ports:
      - "5000:5000"
    depends_on:
      - app2
    restart: unless-stopped

  app2:
    build: ./app2
    container_name: app2
    ports:
      - "5001:5001"
    restart: unless-stopped
    
